name: CI/CD Docker

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/test
  VERSION: ${{ github.sha }}
  NAME: cicd_test

jobs:
  build:
    name: 빌드
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v2
      - name: Docker buildx 설정
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker 레이어 캐시
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: ghcr에 로그인
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: 빌드 및 푸시
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          context: .
          build-args: |
            "STAGE=${{ secrets.STAGE }}"
            "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}"
  deploy:
    needs: build
    name: 배포
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: ghcr에 로그인
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker 실행
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run --add-host=host.docker.internal:host-gateway -d -p 80:3000 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest
